<a href="https://colab.research.google.com/github/Jenniferduong20012004/JennyLearningAI/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
input = torch.randint (5, (1,6,6), dtype = torch.float32)
input



tensor([[[2., 3., 4., 2., 0., 3.],
         [3., 1., 0., 2., 4., 1.],
         [1., 1., 1., 2., 3., 1.],
         [0., 3., 3., 1., 3., 3.],
         [0., 4., 3., 0., 1., 0.],
         [4., 0., 3., 3., 3., 0.]]])

In [7]:
# tạo kernel
conv_layer = torch.nn.Conv2d(
    in_channels=1, #số lượng ma trận input
    out_channels =1, # suố lượng ma trận output
    kernel_size =3, # kernel 3 x 3
    bias = False
)
conv_layer.weight #in ra trọng số

Parameter containing:
tensor([[[[ 0.2067, -0.0247, -0.0202],
          [-0.2024, -0.0374,  0.2953],
          [-0.2067,  0.0532, -0.1470]]]], requires_grad=True)

In [8]:
init_kernel_weight = torch.randint(
    high = 2,
    size = (conv_layer.weight.data.shape),
    dtype = torch.float32
)
init_kernel_weight

tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]])

In [9]:
conv_layer.weight.data = init_kernel_weight

In [10]:
conv_layer.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [11]:
output = conv_layer(input) #nhân elemental wise
output

tensor([[[11.,  9.,  9., 11.],
         [10.,  8.,  9., 11.],
         [ 9.,  9.,  8.,  5.],
         [ 6., 14., 15.,  7.]]], grad_fn=<SqueezeBackward1>)

In [12]:
conv_layer.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [13]:
#nhân bias
output = conv_layer(input)
output

tensor([[[12., 10., 10., 12.],
         [11.,  9., 10., 12.],
         [10., 10.,  9.,  6.],
         [ 7., 15., 16.,  8.]]], grad_fn=<SqueezeBackward1>)

In [14]:
#padding
conv = torch.nn.Conv2d(
    in_channels =1,
    out_channels = 1,
    kernel_size = 3,
    padding = 'same'
)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=same)

In [16]:
conv.weight.data = init_kernel_weight
conv.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [18]:
#bias
conv.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [19]:
output = conv (input)
output

tensor([[[ 5.,  4.,  6., 11.,  8.,  2.],
         [ 6., 12., 10., 10., 12.,  6.],
         [ 5., 11.,  9., 10., 12., 11.],
         [ 6., 10., 10.,  9.,  6.,  7.],
         [ 8.,  7., 15., 16.,  8.,  5.],
         [ 5.,  8.,  5.,  8.,  4.,  5.]]], grad_fn=<SqueezeBackward1>)

In [20]:
#padding cho khác nhau
conv = torch.nn.Conv2d(
    in_channels =1,
    out_channels = 1,
    kernel_size = 3,
    padding = (3,2)
)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(3, 2))

In [23]:
conv.weight.data = init_kernel_weight
conv.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [24]:
#bias
conv.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [25]:
output = conv (input)
output

tensor([[[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
         [ 3.,  6.,  8.,  7.,  3.,  4.,  4.,  1.],
         [ 4.,  5.,  4.,  6., 11.,  8.,  2.,  4.],
         [ 4.,  6., 12., 10., 10., 12.,  6.,  5.],
         [ 4.,  5., 11.,  9., 10., 12., 11.,  3.],
         [ 2.,  6., 10., 10.,  9.,  6.,  7.,  5.],
         [ 5.,  8.,  7., 15., 16.,  8.,  5.,  4.],
         [ 1.,  5.,  8.,  5.,  8.,  4.,  5.,  1.],
         [ 5.,  1.,  8.,  4.,  7.,  4.,  4.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]],
       grad_fn=<SqueezeBackward1>)

In [32]:
#padding cho khác nhau
conv = torch.nn.Conv2d(
    in_channels =1,
    out_channels = 1,
    kernel_size = 3,
    padding = (2,3),
    stride = 2
)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(2, 2), padding=(2, 3))

In [33]:
conv.weight.data = init_kernel_weight
conv.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [34]:
#bias
conv.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [35]:
output = conv (input)
output

tensor([[[ 1.,  6.,  7.,  4.,  1.],
         [ 1.,  6., 10., 12.,  5.],
         [ 1.,  6., 10.,  6.,  5.],
         [ 1.,  5.,  5.,  4.,  1.]]], grad_fn=<SqueezeBackward1>)