<a href="https://colab.research.google.com/github/Jenniferduong20012004/JennyLearningAI/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
input = torch.randint (5, (1,6,6), dtype = torch.float32)
input



tensor([[[4., 3., 0., 4., 3., 2.],
         [0., 1., 4., 3., 3., 0.],
         [2., 2., 2., 2., 3., 2.],
         [0., 4., 3., 3., 1., 1.],
         [2., 3., 4., 1., 2., 1.],
         [1., 0., 1., 1., 0., 4.]]])

In [ ]:
# tạo kernel
conv_layer = torch.nn.Conv2d(
    in_channels=1, #số lượng ma trận input
    out_channels =1, # suố lượng ma trận output
    kernel_size =3, # kernel 3 x 3
    bias = False
)
conv_layer.weight #in ra trọng số

Parameter containing:
tensor([[[[ 0.2067, -0.0247, -0.0202],
          [-0.2024, -0.0374,  0.2953],
          [-0.2067,  0.0532, -0.1470]]]], requires_grad=True)

In [ ]:
init_kernel_weight = torch.randint(
    high = 2,
    size = (conv_layer.weight.data.shape),
    dtype = torch.float32
)
init_kernel_weight

tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]])

In [ ]:
conv_layer.weight.data = init_kernel_weight

In [ ]:
conv_layer.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [ ]:
output = conv_layer(input) #nhân elemental wise
output

tensor([[[11.,  9.,  9., 11.],
         [10.,  8.,  9., 11.],
         [ 9.,  9.,  8.,  5.],
         [ 6., 14., 15.,  7.]]], grad_fn=<SqueezeBackward1>)

In [ ]:
conv_layer.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [ ]:
#nhân bias
output = conv_layer(input)
output

tensor([[[12., 10., 10., 12.],
         [11.,  9., 10., 12.],
         [10., 10.,  9.,  6.],
         [ 7., 15., 16.,  8.]]], grad_fn=<SqueezeBackward1>)

In [ ]:
#padding
conv = torch.nn.Conv2d(
    in_channels =1,
    out_channels = 1,
    kernel_size = 3,
    padding = 'same'
)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=same)

In [ ]:
conv.weight.data = init_kernel_weight
conv.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [ ]:
#bias
conv.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [ ]:
output = conv (input)
output

tensor([[[ 5.,  4.,  6., 11.,  8.,  2.],
         [ 6., 12., 10., 10., 12.,  6.],
         [ 5., 11.,  9., 10., 12., 11.],
         [ 6., 10., 10.,  9.,  6.,  7.],
         [ 8.,  7., 15., 16.,  8.,  5.],
         [ 5.,  8.,  5.,  8.,  4.,  5.]]], grad_fn=<SqueezeBackward1>)

In [ ]:
#padding cho khác nhau
conv = torch.nn.Conv2d(
    in_channels =1,
    out_channels = 1,
    kernel_size = 3,
    padding = (3,2)
)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(3, 2))

In [ ]:
conv.weight.data = init_kernel_weight
conv.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [ ]:
#bias
conv.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [ ]:
output = conv (input)
output

tensor([[[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
         [ 3.,  6.,  8.,  7.,  3.,  4.,  4.,  1.],
         [ 4.,  5.,  4.,  6., 11.,  8.,  2.,  4.],
         [ 4.,  6., 12., 10., 10., 12.,  6.,  5.],
         [ 4.,  5., 11.,  9., 10., 12., 11.,  3.],
         [ 2.,  6., 10., 10.,  9.,  6.,  7.,  5.],
         [ 5.,  8.,  7., 15., 16.,  8.,  5.,  4.],
         [ 1.,  5.,  8.,  5.,  8.,  4.,  5.,  1.],
         [ 5.,  1.,  8.,  4.,  7.,  4.,  4.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]],
       grad_fn=<SqueezeBackward1>)

In [ ]:
#padding cho khác nhau
conv = torch.nn.Conv2d(
    in_channels =1,
    out_channels = 1,
    kernel_size = 3,
    padding = (2,3),
    stride = 2
)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(2, 2), padding=(2, 3))

In [ ]:
conv.weight.data = init_kernel_weight
conv.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [ ]:
#bias
conv.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [ ]:
output = conv (input)
output

tensor([[[ 1.,  6.,  7.,  4.,  1.],
         [ 1.,  6., 10., 12.,  5.],
         [ 1.,  6., 10.,  6.,  5.],
         [ 1.,  5.,  5.,  4.,  1.]]], grad_fn=<SqueezeBackward1>)

In [ ]:
maxPolLayer = torch.nn.MaxPool2d(kernel_size=2)
#default stride =2

In [ ]:
output = maxPolLayer(input)
output

tensor([[[3., 4., 4.],
         [3., 3., 3.],
         [4., 3., 3.]]])

In [ ]:
maxPolLayer = torch.nn.MaxPool1d(kernel_size=3)
#default stride =2

In [ ]:
output = maxPolLayer(input)
output

tensor([[[4., 3.],
         [3., 4.],
         [1., 3.],
         [3., 3.],
         [4., 1.],
         [4., 3.]]])

In [ ]:
avgPolLayer = torch.nn.AvgPool1d(
    kernel_size=3,
    stride =3
)

In [ ]:
output = avgPolLayer(input)

In [2]:
#model
model = torch.nn.Sequential(
    torch.nn.Flatten(), #biến thành vector
    torch.nn.Linear(784, 256), #một hidden layer có 256 nodes nối với 784 nodes phía trước
    torch.nn.ReLU(), #có thể thay thế bằng sigmoid tính a
    torch.nn.Linear (256,10)
)

In [4]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),
                             lr = 0.01)

In [5]:
import tensorflow as tf
from tensorflow import keras

(train_images, train_labels), (test_images, test_labels) = keras.datasets.fashion_mnist.load_data()

print(train_images.shape)
print(test_images.shape)

4422102/4422102 [==============================] - 0s 0us/step
(60000, 28, 28)
(10000, 28, 28)


In [6]:
#reshape
train_images = train_images / 255.0
test_images  = test_images / 255.0

train_images = tf.reshape(train_images, (60000, 28, 28, 1))
test_images  = tf.reshape(test_images, (10000, 28, 28, 1))

print(train_images.shape)
print(test_images.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)
