<a href="https://colab.research.google.com/github/Jenniferduong20012004/JennyLearningAI/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
input = torch.randint (5, (1,6,6), dtype = torch.float32)
input



tensor([[[4., 3., 0., 4., 3., 2.],
         [0., 1., 4., 3., 3., 0.],
         [2., 2., 2., 2., 3., 2.],
         [0., 4., 3., 3., 1., 1.],
         [2., 3., 4., 1., 2., 1.],
         [1., 0., 1., 1., 0., 4.]]])

In [ ]:
# tạo kernel
conv_layer = torch.nn.Conv2d(
    in_channels=1, #số lượng ma trận input
    out_channels =1, # suố lượng ma trận output
    kernel_size =3, # kernel 3 x 3
    bias = False
)
conv_layer.weight #in ra trọng số

Parameter containing:
tensor([[[[ 0.2067, -0.0247, -0.0202],
          [-0.2024, -0.0374,  0.2953],
          [-0.2067,  0.0532, -0.1470]]]], requires_grad=True)

In [ ]:
init_kernel_weight = torch.randint(
    high = 2,
    size = (conv_layer.weight.data.shape),
    dtype = torch.float32
)
init_kernel_weight

tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]])

In [ ]:
conv_layer.weight.data = init_kernel_weight

In [ ]:
conv_layer.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [ ]:
output = conv_layer(input) #nhân elemental wise
output

tensor([[[11.,  9.,  9., 11.],
         [10.,  8.,  9., 11.],
         [ 9.,  9.,  8.,  5.],
         [ 6., 14., 15.,  7.]]], grad_fn=<SqueezeBackward1>)

In [ ]:
conv_layer.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [ ]:
#nhân bias
output = conv_layer(input)
output

tensor([[[12., 10., 10., 12.],
         [11.,  9., 10., 12.],
         [10., 10.,  9.,  6.],
         [ 7., 15., 16.,  8.]]], grad_fn=<SqueezeBackward1>)

In [ ]:
#padding
conv = torch.nn.Conv2d(
    in_channels =1,
    out_channels = 1,
    kernel_size = 3,
    padding = 'same'
)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=same)

In [ ]:
conv.weight.data = init_kernel_weight
conv.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [ ]:
#bias
conv.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [ ]:
output = conv (input)
output

tensor([[[ 5.,  4.,  6., 11.,  8.,  2.],
         [ 6., 12., 10., 10., 12.,  6.],
         [ 5., 11.,  9., 10., 12., 11.],
         [ 6., 10., 10.,  9.,  6.,  7.],
         [ 8.,  7., 15., 16.,  8.,  5.],
         [ 5.,  8.,  5.,  8.,  4.,  5.]]], grad_fn=<SqueezeBackward1>)

In [ ]:
#padding cho khác nhau
conv = torch.nn.Conv2d(
    in_channels =1,
    out_channels = 1,
    kernel_size = 3,
    padding = (3,2)
)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(3, 2))

In [ ]:
conv.weight.data = init_kernel_weight
conv.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [ ]:
#bias
conv.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [ ]:
output = conv (input)
output

tensor([[[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
         [ 3.,  6.,  8.,  7.,  3.,  4.,  4.,  1.],
         [ 4.,  5.,  4.,  6., 11.,  8.,  2.,  4.],
         [ 4.,  6., 12., 10., 10., 12.,  6.,  5.],
         [ 4.,  5., 11.,  9., 10., 12., 11.,  3.],
         [ 2.,  6., 10., 10.,  9.,  6.,  7.,  5.],
         [ 5.,  8.,  7., 15., 16.,  8.,  5.,  4.],
         [ 1.,  5.,  8.,  5.,  8.,  4.,  5.,  1.],
         [ 5.,  1.,  8.,  4.,  7.,  4.,  4.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]],
       grad_fn=<SqueezeBackward1>)

In [ ]:
#padding cho khác nhau
conv = torch.nn.Conv2d(
    in_channels =1,
    out_channels = 1,
    kernel_size = 3,
    padding = (2,3),
    stride = 2
)
conv

Conv2d(1, 1, kernel_size=(3, 3), stride=(2, 2), padding=(2, 3))

In [ ]:
conv.weight.data = init_kernel_weight
conv.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 0., 0.],
          [0., 1., 1.]]]], requires_grad=True)

In [ ]:
#bias
conv.bias = torch.nn.Parameter(
    torch.tensor ([1], dtype = torch.float32)
)
conv.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [ ]:
output = conv (input)
output

tensor([[[ 1.,  6.,  7.,  4.,  1.],
         [ 1.,  6., 10., 12.,  5.],
         [ 1.,  6., 10.,  6.,  5.],
         [ 1.,  5.,  5.,  4.,  1.]]], grad_fn=<SqueezeBackward1>)

In [ ]:
maxPolLayer = torch.nn.MaxPool2d(kernel_size=2)
#default stride =2

In [ ]:
output = maxPolLayer(input)
output

tensor([[[3., 4., 4.],
         [3., 3., 3.],
         [4., 3., 3.]]])

In [ ]:
maxPolLayer = torch.nn.MaxPool1d(kernel_size=3)
#default stride =2

In [ ]:
output = maxPolLayer(input)
output

tensor([[[4., 3.],
         [3., 4.],
         [1., 3.],
         [3., 3.],
         [4., 1.],
         [4., 3.]]])

In [ ]:
avgPolLayer = torch.nn.AvgPool1d(
    kernel_size=3,
    stride =3
)

In [ ]:
output = avgPolLayer(input)

In [ ]:
#model
model = torch.nn.Sequential(
    torch.nn.Flatten(), #biến thành vector
    torch.nn.Linear(784, 256), #một hidden layer có 256 nodes nối với 784 nodes phía trước
    torch.nn.ReLU(), #có thể thay thế bằng sigmoid tính a
    torch.nn.Linear (256,10)
)

In [ ]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),
                             lr = 0.01)

In [ ]:
import tensorflow as tf
from tensorflow import keras

(train_images, train_labels), (test_images, test_labels) = keras.datasets.fashion_mnist.load_data()

print(train_images.shape)
print(test_images.shape)

4422102/4422102 [==============================] - 0s 0us/step
(60000, 28, 28)
(10000, 28, 28)


In [ ]:
#reshape
train_images = train_images / 255.0
test_images  = test_images / 255.0

train_images = tf.reshape(train_images, (60000, 28, 28, 1))
test_images  = tf.reshape(test_images, (10000, 28, 28, 1))

print(train_images.shape)
print(test_images.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [ ]:
# model
model = keras.models.Sequential()

# input is with the shape of (28, 28, 1)
model.add(tf.keras.Input(shape=(28, 28, 1)))

# Convolve with 1 (7x7) kernel
# Output: (22x22x32)
model.add(keras.layers.Conv2D(32, (7, 7), activation='relu'))

# Convolve with 2 (7x7) kernel
# Output: (16x16x64)
model.add(keras.layers.Conv2D(64, (7, 7), activation='relu'))

# Convolve with 3 (7x7) kernel
# Output: (10x10x128)
model.add(keras.layers.Conv2D(128, (7, 7), activation='relu'))

# Convolve with 4 (7x7) kernel
# Output: (4x4x256)
model.add(keras.layers.Conv2D(256, (7, 7), activation='relu'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 22, 22, 32)        1600      
                                                                 
 conv2d_1 (Conv2D)           (None, 16, 16, 64)        100416    
                                                                 
 conv2d_2 (Conv2D)           (None, 10, 10, 128)       401536    
                                                                 
 conv2d_3 (Conv2D)           (None, 4, 4, 256)         1605888   
                                                                 
Total params: 2109440 (8.05 MB)
Trainable params: 2109440 (8.05 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
import tensorflow as tf
from tensorflow import keras

model = keras.models.Sequential()
model.add(tf.keras.Input(shape=(28, 28, 1)))
model.add(keras.layers.Conv2D(32, (7, 7), activation='relu'))
model.add(keras.layers.Conv2D(64, (7, 7), activation='relu'))
model.add(keras.layers.Conv2D(128, (7, 7), activation='relu'))
model.add(keras.layers.Conv2D(256, (7, 7), activation='relu'))

# classifier
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(128, activation='relu'))
model.add(keras.layers.Dense(10, activation='softmax'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 22, 22, 32)        1600      
                                                                 
 conv2d_5 (Conv2D)           (None, 16, 16, 64)        100416    
                                                                 
 conv2d_6 (Conv2D)           (None, 10, 10, 128)       401536    
                                                                 
 conv2d_7 (Conv2D)           (None, 4, 4, 256)         1605888   
                                                                 
 flatten (Flatten)           (None, 4096)              0         
                                                                 
 dense (Dense)               (None, 128)               524416    
                                                                 
 dense_1 (Dense)             (None, 10)               

In [3]:
import torch
import torch.nn as nn
conv_layer = nn.Conv2d(1, 2,3) #input channel có chiều sâu bao nhiu, output có chiều sâu bao nhiêu
#in channel: chiều sâu input, out channel: chiều sâu output: số lượng kernel, kernel size: shape kernel

In [4]:
print (conv_layer.weight.shape) #chiều sâu input = chiều sâu kernel --> 1,3,3

torch.Size([2, 1, 3, 3])


In [6]:
print (conv_layer.bias.shape) # 2 kernel --> 2 bias

torch.Size([2])


In [8]:
print (conv_layer.weight)
print (conv_layer.bias)

Parameter containing:
tensor([[[[-0.3111,  0.1510,  0.1884],
          [ 0.2903,  0.1909, -0.1012],
          [-0.0337,  0.0261, -0.0060]]],


        [[[-0.0897, -0.0023, -0.1301],
          [-0.0250, -0.0726, -0.0410],
          [-0.0617,  0.3100, -0.0420]]]], requires_grad=True)
Parameter containing:
tensor([ 0.1890, -0.0865], requires_grad=True)


In [9]:
#hàm sinh ra data ngẫu nhiên
data = torch.randn((1,7,7))
print (data)

tensor([[[-2.2660e+00, -2.1850e-01,  8.3923e-01, -6.0473e-03, -2.1842e+00,
          -1.9854e+00, -2.9913e-01],
         [ 2.2550e-01,  1.4847e+00, -7.8768e-01,  2.3811e-03, -1.1656e-01,
           4.9633e-01,  5.3405e-01],
         [ 1.6674e+00, -1.0932e+00, -2.1973e-01,  1.5255e+00,  4.3091e-01,
           2.8957e-01,  2.1685e+00],
         [ 9.8681e-01, -1.7475e+00,  1.6786e+00, -1.3536e+00,  5.7550e-01,
           3.5971e-01,  5.0990e-01],
         [-1.0265e+00,  3.3996e-01,  9.2173e-01,  2.7727e+00,  2.7079e-02,
          -1.1504e-01, -1.8263e+00],
         [ 3.4054e-01, -2.0770e-01, -1.0735e+00,  1.0125e+00, -5.4347e-01,
           4.6061e-01,  1.0194e-01],
         [ 1.1292e+00,  2.8722e-01, -1.0335e-01, -1.3506e+00,  1.1911e+00,
          -1.5515e+00,  7.8800e-01]]])


In [10]:
#train data
output = conv_layer(data)
print (output.shape)
print (output)

torch.Size([2, 5, 5])
tensor([[[ 1.3643,  0.6849, -0.6562, -0.6268,  0.4991],
         [ 0.4033, -0.7942,  0.5010,  0.8184,  0.3486],
         [-0.7154,  0.7294,  0.7806, -0.5775,  0.6984],
         [-0.4025,  0.6981,  0.4308,  1.5354,  0.3609],
         [ 0.8713,  0.3729,  0.2240, -0.4617, -0.3463]],

        [[-0.5056, -0.1127,  0.6151,  0.1929,  0.0701],
         [-0.6341,  0.4476, -0.6710,  0.0146, -0.2128],
         [-0.0415, -0.0608,  0.7080, -0.4427, -0.4300],
         [-0.4665, -0.3092, -0.1314, -0.3300,  0.0494],
         [-0.0407, -0.4313, -0.6660,  0.1927, -0.4627]]],
       grad_fn=<SqueezeBackward1>)


In [11]:
model = nn.Sequential(conv_layer, nn.ReLU()) #model đi qua layer (kernel) và relu

In [12]:
print (model)

Sequential(
  (0): Conv2d(1, 2, kernel_size=(3, 3), stride=(1, 1))
  (1): ReLU()
)


In [13]:
from torchsummary import summary
summary (model, (1,9,9))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1              [-1, 2, 7, 7]              20
              ReLU-2              [-1, 2, 7, 7]               0
Total params: 20
Trainable params: 20
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [15]:
output = model(data)
print (output)
print (output.shape)

tensor([[[1.3643, 0.6849, 0.0000, 0.0000, 0.4991],
         [0.4033, 0.0000, 0.5010, 0.8184, 0.3486],
         [0.0000, 0.7294, 0.7806, 0.0000, 0.6984],
         [0.0000, 0.6981, 0.4308, 1.5354, 0.3609],
         [0.8713, 0.3729, 0.2240, 0.0000, 0.0000]],

        [[0.0000, 0.0000, 0.6151, 0.1929, 0.0701],
         [0.0000, 0.4476, 0.0000, 0.0146, 0.0000],
         [0.0000, 0.0000, 0.7080, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0494],
         [0.0000, 0.0000, 0.0000, 0.1927, 0.0000]]], grad_fn=<ReluBackward0>)
torch.Size([2, 5, 5])


In [18]:
fullyConnectLayer = nn.Linear(7,10) #input có 7 số, output có 10, quan tâm đến chiều sâu

In [19]:
output = fullyConnectLayer (data)
print (output)

tensor([[[-0.4241,  1.8346, -0.1882, -0.8662, -1.2796,  0.7490,  0.2491,
           0.4181, -0.4456,  1.5756],
         [-0.4861,  0.2277, -0.1584,  0.3808,  0.0814, -0.4417, -0.6915,
          -0.1086,  0.8229, -0.2163],
         [ 0.1197,  0.4051,  0.4018,  0.0157,  1.7273, -0.6006, -0.9126,
          -1.0255,  0.4780, -1.0628],
         [ 0.5352,  0.3069,  0.6579, -0.5154,  0.2681, -0.0490,  0.3984,
          -0.4976,  0.0596, -0.3747],
         [-1.6662, -0.5618,  0.3317, -2.0492,  0.0512, -0.0701, -0.5751,
           0.8351, -0.8550,  0.3188],
         [-0.0824,  0.1768,  0.2340, -0.1498,  0.5237, -0.9706, -0.8932,
          -0.5787,  0.6059, -0.3571],
         [ 0.4040,  0.7208, -0.5842,  0.3859,  0.0316,  0.3964, -0.2741,
          -0.9597,  0.8399, -0.4685]]], grad_fn=<ViewBackward0>)
