<a href="https://colab.research.google.com/github/Jenniferduong20012004/JennyLearningAI/blob/main/vector_and_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#add vector
#by list comprehension
import numpy as np
def add_vector(v1,v2):
  result = [v1[i]+v2[i] for i in range (len(v1))]
  return result
#by zip
def add_v(v1,v2):
  return [v1+v2 for v1,v2 in zip(v1,v2)]
data1 = np.array([1,2,3])
data2 = np.array ([5,6,7])
print (add_vector(data1, data2))
print (data1+data2)
print (add_v(data1, data2))

[6, 8, 10]
[ 6  8 10]
[6, 8, 10]


In [4]:
#minus vector
result = data1-data2
print (result)

[-4 -4 -4]


In [6]:
#division and hadamard multiple vector
resultdiv = data1/data2
resultmul = data1*data2
print (resultdiv, resultmul)

[0.2        0.33333333 0.42857143] [ 5 12 21]


In [7]:
#zeros
import numpy as np
data = np.zeros((1,2))
print (data)

[[0. 0.]]


In [10]:
test = [[0]*5 for i in range (3)]
print (test)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [12]:
#where
data_where = np.array([1,2,3,4,5,6])
result = np.where (data_where<=3,0,data_where) # condition, true, false
print (result)

[0 0 0 4 5 6]
